In [12]:
#read the csv file
import pandas as pd
can = pd.read_csv("https://raw.githubusercontent.com/medcab9/ds/master/data/Cannabis%20StrainsFeatures%20-%20cannabis.csv")
print(can.shape)
can.head()

(2351, 6)


Strain    Type  Rating                                     Effects  \
0          100-Og  hybrid     4.0  Creative,Energetic,Tingly,Euphoric,Relaxed   
1  98-White-Widow  hybrid     4.7    Relaxed,Aroused,Creative,Happy,Energetic   
2            1024  sativa     4.4   Uplifted,Happy,Relaxed,Energetic,Creative   
3        13-Dawgs  hybrid     4.2     Tingly,Creative,Hungry,Relaxed,Uplifted   
4        24K-Gold  hybrid     4.6   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  
0  $100 OG is a 50/50 hybrid strain that packs a ...  
1  The ‘98 Aloha White Widow is an especially pot...  
2  1024 is a sativa-dominant hybrid bred in Spain...  
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...  
4  Also known as Kosher Tangie, 24k Gold is a 60%...

In [13]:
can.describe(include='all')

Strain    Type       Rating Effects Flavor Description
count        2351    2351  2351.000000    2351   2350        2350
unique       2350       3          NaN    1704   1349        2343
top     B-Witched  hybrid          NaN    None   None        None
freq            2    1212          NaN      29     44           5
mean          NaN     NaN     4.382561     NaN    NaN         NaN
std           NaN     NaN     0.639090     NaN    NaN         NaN
min           NaN     NaN     0.000000     NaN    NaN         NaN
25%           NaN     NaN     4.200000     NaN    NaN         NaN
50%           NaN     NaN     4.500000     NaN    NaN         NaN
75%           NaN     NaN     4.700000     NaN    NaN         NaN
max           NaN     NaN     5.000000     NaN    NaN         NaN

In [14]:
can.isnull().sum()

Strain         0
Type           0
Rating         0
Effects        0
Flavor         1
Description    1
dtype: int64

In [15]:
# Cleaning the data and changing nan values to unknowns and 0s
import numpy as np

can['Rating'] = can['Rating'].replace(np.nan, 0)
can['Effects'] = can['Effects'].replace(np.nan, 'Effects currently unknown')
can['Flavor'] = can['Flavor'].replace(np.nan, 'Flavor profile currently unavailable')
can['Description'] = can['Description'].replace(np.nan, 'Strain description currently unavailable')
can['Type'] = can['Type'].replace(np.nan, 'Type currently unknown')


In [16]:
can.isnull().sum()

Strain         0
Type           0
Rating         0
Effects        0
Flavor         0
Description    0
dtype: int64

In [17]:
# Unique Strain types

can.Strain.value_counts()

B-Witched              2
Sugar-Shack            1
Snowland               1
Jack-Smack             1
Kona-Gold              1
                      ..
Snoop-S-Dream          1
Dog-Shit               1
Blackberry-Pie         1
Alpha-Cow              1
South-Indian-Indica    1
Name: Strain, Length: 2350, dtype: int64

In [18]:
can['Rating'].unique()

array([4. , 4.7, 4.4, 4.2, 4.6, 4.5, 4.3, 5. , 3.8, 4.1, 4.8, 3.4, 3.7,
       3.9, 0. , 3. , 4.9, 3.6, 2.8, 3.3, 3.5, 3.2, 1. , 3.1, 2.5])

In [31]:
# Create new series with information

can['total_text'] = can['Strain'] + can['Effects'] + can['Description']+can["Flavor"]

In [32]:
can.head()

Strain    Type  Rating                                     Effects  \
0          100-Og  hybrid     4.0  Creative,Energetic,Tingly,Euphoric,Relaxed   
1  98-White-Widow  hybrid     4.7    Relaxed,Aroused,Creative,Happy,Energetic   
2            1024  sativa     4.4   Uplifted,Happy,Relaxed,Energetic,Creative   
3        13-Dawgs  hybrid     4.2     Tingly,Creative,Hungry,Relaxed,Uplifted   
4        24K-Gold  hybrid     4.6   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   
1  The ‘98 Aloha White Widow is an especially pot...   
2  1024 is a sativa-dominant hybrid bred in Spain...   
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...   
4  Also known as Kosher Tangie, 24k Gold is a 60%...   

                                          total_text  \
0  100-OgCreative,Energetic,Tingly,Euphoric,Relax...   
1  98-White-WidowRelaxed,Aroused,Creative,Happy,E...   
2  1024Uplifted,Happy,Relaxed,Energetic,Creative1...   
3  13-DawgsTingly,Creative,Hungry,Relaxed,Uplifte...   
4  24K-GoldHappy,Relaxed,Euphoric,Uplifted,Talkat...   

                                        spaCy_tokens  
0  [100-ogcreative,energetic,tingly,euphoric,rela...  
1  [98-white-widowrelaxed,aroused,creative,happy,...  
2  [1024uplifted,happy,relaxed,energetic,creative...  
3  [13-dawgstingly,creative,hungry,relaxed,uplift...  
4  [24k-goldhappy,relaxed,euphoric,uplifted,talka...

In [11]:
# df = pd.read_csv("nn_model_strains.csv")
# df.head()

Unnamed: 0          Strain    Type  \
0           0          100-Og  hybrid   
1           1  98-White-Widow  hybrid   
2           2            1024  sativa   
3           3        13-Dawgs  hybrid   
4           4        24K-Gold  hybrid   

                                      Effects                     Flavor  \
0  Creative,Energetic,Tingly,Euphoric,Relaxed        Earthy,Sweet,Citrus   
1    Relaxed,Aroused,Creative,Happy,Energetic      Flowery,Violet,Diesel   
2   Uplifted,Happy,Relaxed,Energetic,Creative    Spicy/Herbal,Sage,Woody   
3     Tingly,Creative,Hungry,Relaxed,Uplifted  Apricot,Citrus,Grapefruit   
4   Happy,Relaxed,Euphoric,Uplifted,Talkative       Citrus,Earthy,Orange   

                                         Description  name  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   NaN   
1  The ‘98 Aloha White Widow is an especially pot...   NaN   
2  1024 is a sativa-dominant hybrid bred in Spain...  1024   
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...   NaN   
4  Also known as Kosher Tangie, 24k Gold is a 60%...   NaN   

                                  ailment  \
0                                     NaN   
1                                     NaN   
2  Stress, Pain, Depression, Inflammation   
3                                     NaN   
4                                     NaN   

                                            all_text  \
0  100-Og hybrid Creative,Energetic,Tingly,Euphor...   
1  98-White-Widow hybrid Relaxed,Aroused,Creative...   
2  1024 sativa Uplifted,Happy,Relaxed,Energetic,C...   
3  13-Dawgs hybrid Tingly,Creative,Hungry,Relaxed...   
4  24K-Gold hybrid Happy,Relaxed,Euphoric,Uplifte...   

                                              lemmas  
0  100-Og hybrid Creative energetic Tingly Euphor...  
1  98-white widow hybrid Relaxed arouse Creative ...  
2  1024 sativa Uplifted happy relaxed energetic C...  
3  13-dawgs hybrid Tingly creative hungry Relaxed...  
4  24k gold hybrid Happy Relaxed Euphoric Uplifte...

In [22]:
# df.shape

## 2) Use Spacy to tokenize the total text

In [33]:
import re
import string

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import spacy
from spacy.tokenizer import Tokenizer
from bs4 import BeautifulSoup

In [34]:
# Inialize spaCy model and tokenizer
nlp = spacy.load("en_core_web_lg")
tokenizer = Tokenizer(nlp.vocab)

In [35]:
tokens = []

# Return lower case tokens and ignore stop words/punctuation
for doc in tokenizer.pipe(can['total_text'], batch_size=500):
    
    doc_tokens = []
    
    for token in doc:
        # ignore stopwords, spaces and punctuation
        if (token.is_stop == False) & (token.is_punct == False) & (token.is_space == False):
            doc_tokens.append(token.text.lower())

    tokens.append(doc_tokens)

can['spaCy_tokens'] = tokens
can['spaCy_tokens'].head()

0    [100-ogcreative,energetic,tingly,euphoric,rela...
1    [98-white-widowrelaxed,aroused,creative,happy,...
2    [1024uplifted,happy,relaxed,energetic,creative...
3    [13-dawgstingly,creative,hungry,relaxed,uplift...
4    [24k-goldhappy,relaxed,euphoric,uplifted,talka...
Name: spaCy_tokens, dtype: object

In [26]:
print(can.shape)
can.head()

(2351, 8)


Strain    Type  Rating                                     Effects  \
0          100-Og  hybrid     4.0  Creative,Energetic,Tingly,Euphoric,Relaxed   
1  98-White-Widow  hybrid     4.7    Relaxed,Aroused,Creative,Happy,Energetic   
2            1024  sativa     4.4   Uplifted,Happy,Relaxed,Energetic,Creative   
3        13-Dawgs  hybrid     4.2     Tingly,Creative,Hungry,Relaxed,Uplifted   
4        24K-Gold  hybrid     4.6   Happy,Relaxed,Euphoric,Uplifted,Talkative   

                      Flavor  \
0        Earthy,Sweet,Citrus   
1      Flowery,Violet,Diesel   
2    Spicy/Herbal,Sage,Woody   
3  Apricot,Citrus,Grapefruit   
4       Citrus,Earthy,Orange   

                                         Description  \
0  $100 OG is a 50/50 hybrid strain that packs a ...   
1  The ‘98 Aloha White Widow is an especially pot...   
2  1024 is a sativa-dominant hybrid bred in Spain...   
3  13 Dawgs is a hybrid of G13 and Chemdawg genet...   
4  Also known as Kosher Tangie, 24k Gold is a 60%...   

                                          total_text  \
0  100-OgCreative,Energetic,Tingly,Euphoric,Relax...   
1  98-White-WidowRelaxed,Aroused,Creative,Happy,E...   
2  1024Uplifted,Happy,Relaxed,Energetic,Creative1...   
3  13-DawgsTingly,Creative,Hungry,Relaxed,Uplifte...   
4  24K-GoldHappy,Relaxed,Euphoric,Uplifted,Talkat...   

                                        spaCy_tokens  
0  [100-ogcreative,energetic,tingly,euphoric,rela...  
1  [98-white-widowrelaxed,aroused,creative,happy,...  
2  [1024uplifted,happy,relaxed,energetic,creative...  
3  [13-dawgstingly,creative,hungry,relaxed,uplift...  
4  [24k-goldhappy,relaxed,euphoric,uplifted,talka...

## Part 2: Vector Representation

In [27]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,TfidfTransformer

In [28]:
def gather_data(df_column):
    """ Produces List of Documents from a df column    
    returns list of strings 
    """
    
    #data = []
    
#     for row in df_column:
#         data.append(' '.join(str(row))
    data = [''.join(str(item)) for item in df_column]
        
    
    return data

In [30]:
data = gather_data(can['spaCy_tokens'])
data[0]

"['100-ogcreative,energetic,tingly,euphoric,relaxed$100', 'og', '50/50', 'hybrid', 'strain', 'packs', 'strong', 'punch.', 'supposedly', 'refers', 'strength', 'high', 'price', 'started', 'showing', 'hollywood.', 'plant,', '$100', 'og', 'tends', 'produce', 'large', 'dark', 'green', 'buds', 'stems.', 'users', 'report', 'strong', 'body', 'effect', 'indica', 'pain', 'relief', 'alert,', 'cerebral', 'feeling', 'thanks', 'sativa', 'side.flavor']"

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

# create the transformer
vect = CountVectorizer()

# build vocab

vect.fit(data)

# transform text
dtm = vect.transform(data)
print(dtm.shape)

(2351, 12062)


In [37]:
# Tunning Parameters

# Instantiate vectorizer object
tfidf = TfidfVectorizer(stop_words='english',
                         ngram_range = (1,2),
                        max_df=.97,
                        min_df=3)
                        #tokenizer=tokenize)

# Create a vocabulary and get word counts per document
dtm = tfidf.fit_transform(data)


# Get feature names to use as dataframe column headers
dtm = pd.DataFrame(dtm.todense(), columns=tfidf.get_feature_names())

# View Feature Matrix as DataFrame
dtm.head()

09  09 cookies   10  10 11  10 feet  10 week  10 weeks      100  \
0  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.45837   
1  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.00000   
2  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.00000   
3  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.00000   
4  0.0         0.0  0.0    0.0      0.0      0.0       0.0  0.00000   

   100 sativa   11  ...  yunnan  zealand  zest  zestful  zesty  zesty lemon  \
0         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   
1         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   
2         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   
3         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   
4         0.0  0.0  ...     0.0      0.0   0.0      0.0    0.0          0.0   

   zion  zion botanicals  zombie  zombie og  
0   0.0              0.0     0.0        0.0  
1   0.0              0.0     0.0        0.0  
2   0.0              0.0     0.0        0.0  
3   0.0              0.0     0.0        0.0  
4   0.0              0.0     0.0        0.0  

[5 rows x 9473 columns]

In [38]:
from sklearn.neighbors import NearestNeighbors

# Fit on TF-IDF Vectors
nn  = NearestNeighbors(n_neighbors=5, algorithm='kd_tree')
nn.fit(dtm)

NearestNeighbors(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [39]:
# get the top 5 nearest neighbors
nn.kneighbors([dtm.iloc[0].values])

(array([[0.        , 1.28437438, 1.30300541, 1.31476649, 1.31774124]]),
 array([[   0,  682,  959,  237, 1891]], dtype=int64))

In [40]:
# Write out fake 


fake_input= [" I am looking for something which helps with my anxiety  and helps me go to sleep. I like it to have fruity flavour "]

print(fake_input)

[' I am looking for something which helps with my anxiety  and helps me go to sleep. I like it to have fruity flavour ']


In [42]:
new = tfidf.transform(fake_input)
new

<1x9473 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [43]:
nn.kneighbors(new.todense())

(array([[1.30223187, 1.30695919, 1.31023683, 1.32285729, 1.32408118]]),
 array([[ 411, 1889,  343,  153, 2318]], dtype=int64))

In [45]:
# Print two results

print("Recommendation 1---",can['total_text'][411])

print("Recommendation 2---",can['total_text'][1889])

Recommendation 1--- ButterscotchRelaxed,Euphoric,Focused,Creative,SleepyButterscotch is a treat of a strain that gets its name from its distinctive candy aroma. This strong indica helps patients to gain some mental peace and unwind from a stressful day. Effects tend to be sedative and sleep-inducing, so Butterscotch is a good choice for treating insomnia.Pine,Citrus,Nutty
Recommendation 2--- SkywalkerRelaxed,Euphoric,Sleepy,Happy,UpliftedSkywalker is a well-rounded indica-dominant hybrid that helps patients knock out pain and relax into sleep after a long day of battling the Dark Side. The sativa side of this strain allows for a nice head high as well, but it isn’t overly hazy or unfocused. Skywalker was created by Amsterdam’s Dutch Passion Seeds to combine the sweet fruity aroma of Blueberry with the growing strengths of the hardy, high-yielding Mazar. Great for indoor growing, Skywalker plants will stay shorter and bushy, flowering in 8 to 9 weeks. If you’re looking for the Californi

In [53]:
response = can[['Strain','Type', "Rating",'Effects', 'Flavor', 'Description']].iloc[[411]]
response

Strain    Type  Rating                                   Effects  \
411  Butterscotch  indica     4.3  Relaxed,Euphoric,Focused,Creative,Sleepy   

                Flavor                                        Description  
411  Pine,Citrus,Nutty  Butterscotch is a treat of a strain that gets ...

In [54]:
response.to_json(orient='records')

'[{"Strain":"Butterscotch","Type":"indica","Rating":4.3,"Effects":"Relaxed,Euphoric,Focused,Creative,Sleepy","Flavor":"Pine,Citrus,Nutty","Description":"Butterscotch is a treat of a strain that gets its name from its distinctive candy aroma. This strong indica helps patients to gain some mental peace and unwind from a stressful day. Effects tend to be sedative and sleep-inducing, so Butterscotch is a good choice for treating insomnia."}]'

In [55]:
import pickle

with open('knn_model.pkl', 'wb') as f:
    pickle.dump(nn, f)